# Generated by Django 5.1.3 on 2024-11-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            #field=models.SlugField(default='example.slug', unique=True),
            field=models.CharField(max_length=255,blank=True,null=True),
            preserve_default=False,
        ),
    ]
