# Generated by Django 5.1.3 on 2024-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            #field=models.SlugField(default=1, unique=True),
            field=models.CharField(max_length=255,blank=True,null=True),
            preserve_default=False,
            
        ),
    ]
